# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 02:38
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('vote', models.IntegerField(verbose_name='点赞数')),
                ('obj_id', models.IntegerField(default=0, verbose_name='回复给谁')),
            ],
            options={
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='LanMu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanmu', models.CharField(max_length=256, verbose_name='栏目')),
            ],
            options={
                'verbose_name': '栏目',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='column_name')),
                ('intro', models.TextField(default='', verbose_name='introduction')),
                ('lanmu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.LanMu', verbose_name='所属栏目')),
            ],
            options={
                'verbose_name': 'Tag',
                'ordering': ['name'],
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Tie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_top', models.BooleanField(default=False, verbose_name='设为置顶')),
                ('solved', models.BooleanField(default=False, verbose_name='是否结帖')),
                ('wonderful', models.BooleanField(default=False, verbose_name='是精华')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('see_num', models.IntegerField(default=0, verbose_name='浏览数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Tag', verbose_name='小标签')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Tie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
