# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20170802_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='lanmu',
        ),
    ]
