# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_tie_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='手机号')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('danwei', models.CharField(max_length=100, verbose_name='单位')),
                ('zhiwu', models.CharField(max_length=100, verbose_name='职务')),
                ('user_pic', models.ImageField(default='uploads/images/defualt_user_pic.jpg', upload_to='uploads/user_pics/images/', verbose_name='文章标头图片535*270')),
            ],
            options={
                'verbose_name': '网站手机号注册用户',
            },
        ),
        migrations.AlterModelOptions(
            name='tie',
            options={'verbose_name': 'ties', 'verbose_name_plural': '帖子'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='puter',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='tie',
        ),
    ]
