# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20170802_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
