# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20170802_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tie',
            options={'ordering': ['set_top', '-pub_date'], 'verbose_name': 'ties', 'verbose_name_plural': '帖子'},
        ),
        migrations.AddField(
            model_name='comment',
            name='put_wonderful',
            field=models.BooleanField(default=False, verbose_name='最佳答案'),
        ),
    ]
