# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170706_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'article', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='sliderpic',
            options={'verbose_name': '首页4图670x280'},
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True, verbose_name='发布|热点F'),
        ),
        migrations.AlterField(
            model_name='sliderpic',
            name='img',
            field=models.ImageField(default='uploads/blog/images/default.jpg', upload_to='uploads/blog/images/', verbose_name='文章图片670x280'),
        ),
    ]
