# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170802_1040'),
        ('blog', '0005_auto_20170711_1511'),
    ]

    operations = [
    ]
