# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_20170802_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderpic',
            name='url',
            field=models.CharField(default='#', max_length=111, verbose_name='链接URL'),
        ),
    ]
